CREATE DATABASE transport;
USE transport;

CREATE TABLE calendar(
idx SERIAL AUTO_INCREMENT PRIMARY KEY,
ddates DATE NOT NULL);

CREATE TABLE hours(
idx SERIAL AUTO_INCREMENT PRIMARY KEY,
hours TIME NOT NULL);

CREATE TABLE method(
idx SERIAL AUTO_INCREMENT PRIMARY KEY,
method VARCHAR(50) NOT NULL);

CREATE TABLE bulkinfo (
ddate INT NOT NULL,
hours INT NOT NULL,
passangers INT NOT NULL,
method_idx INT NOT NULL);

CREATE TABLE bus(
idx SERIAL AUTO_INCREMENT PRIMARY KEY,
ddate_id INT NOT NULL,
hours_id BIGINT UNSIGNED NOT NULL,
passangers INT NOT NULL,
method_id BIGINT UNSIGNED NOT NULL,
FOREIGN KEY(method_id) REFERENCES method(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY(hours_id) REFERENCES hours(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY(ddate_id) REFERENCES calendar(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT);

CREATE TABLE metro(
idx SERIAL AUTO_INCREMENT PRIMARY KEY,
ddate_id INT NOT NULL,
hours_id BIGINT UNSIGNED NOT NULL,
passangers INT NOT NULL,
method_id BIGINT UNSIGNED NOT NULL,
FOREIGN KEY(method_id) REFERENCES method(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY(hours_id) REFERENCES hours(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY(ddate_id) REFERENCES calendar(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT);

CREATE TABLE cablecar(
idx SERIAL AUTO_INCREMENT PRIMARY KEY,
ddate_id INT NOT NULL,
hours_id BIGINT UNSIGNED NOT NULL,
passangers INT NOT NULL,
method_id BIGINT UNSIGNED NOT NULL,
FOREIGN KEY(method_id) REFERENCES method(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY(hours_id) REFERENCES hours(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY(ddate_id) REFERENCES calendar(idx)
ON UPDATE CASCADE
ON DELETE RESTRICT);